### ISSUE TITLE
FAQ page suggestions

### ISSUE THREAD

**Issue by ttmc** [ipdb/site#1]
In the FAQ page, one question is "Why is IPDB better than a normal database?"

The answer lists five blockchain characteristics that are added to a traditional database: 1) decentralized control, 2) immutability, 3) Sybil tolerance, 4) native assets, and 5) native asset transfer.

I would add two more: 6) public writability, and 7) public readability.

**Comment by gmcmullen** [comment]
Working on that file right now. Currently reads:

### Is IPDB a blockchain?

IPDB brings blockchain characteristics to an open source big data database: 1) decentralized control, 2) immutability, 3) [Sybil tolerance](https://en.wikipedia.org/wiki/Sybil_attack), 4) native assets, 5) native asset transfer, 6) public writability, and 7) public readability. 

I'll merge in what I have done.

**Comment by trentmc** [comment]
We shouldn't have "IPDB" publicly mentioned anywhere, until the big
announce on June 8. Before then, we just say "we're working towards a
public BigchainDB".

Re: "1) decentralized control, 2) immutability, 3) Sybil tolerance, 4)
native assets, and 5) native asset transfer. 6) public writability, and 7)
public readability."

This is a confusing story. Too many details, too long of a list. Better to
stick with the three that we have used extensively elsewhere: 1)
decentralized control 2) immutability 3) assets. Sybil tolerance comes for
free anytime you have a federation (of non anonymous nodes), ie in any FT
or BFT database. Public writability and readability is also not a
breakthrough from a permissioning standpoint. Troy if you really want to
include Sybil tolerance, public writability, and public readabiliyt, then I
suggest a "bonus features" section.

On Tue, Mar 8, 2016 at 2:33 PM, Greg McMullen notifications@github.com
wrote:

> Working on that file right now. Currently reads:
> Is IPDB a blockchain?
> 
> IPDB brings blockchain characteristics to an open source big data
> database: 1) decentralized control, 2) immutability, 3) Sybil tolerance
> https://en.wikipedia.org/wiki/Sybil_attack, 4) native assets, 5) native
> asset transfer, 6) public writability, and 7) public readability.
> 
> I'll merge in what I have done.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ipdb/website/issues/1#issuecomment-193786003.

## 

Follow me at @trentmc0 https://twitter.com/trentmc0
http://trent.st

**Comment by gmcmullen** [comment]
> We shouldn't have "IPDB" publicly mentioned anywhere, until the big
> announce on June 8. Before then, we just say "we're working towards a
> public BigchainDB".

That is the plan, yes. This content is meant for the website that will be launching June 8.

The one exception is the LOIs with Caretakers that will be with the IPDB Foundation.

**Comment by trentmc** [comment]
Perfect

On Tue, Mar 8, 2016 at 3:56 PM, Greg McMullen notifications@github.com
wrote:

> We shouldn't have "IPDB" publicly mentioned anywhere, until the big
> announce on June 8. Before then, we just say "we're working towards a
> public BigchainDB".
> 
> That is the plan, yes. This content is meant for the website that will be
> launching June 8.
> 
> The one exception is the LOIs with Caretakers that will be with the IPDB
> Foundation.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ipdb/website/issues/1#issuecomment-193813697.

## 

Follow me at @trentmc0 https://twitter.com/trentmc0
http://trent.st

**Comment by kremalicious** [comment]
closing this, we're resurrecting this repo for the new ipdb.io
