### ISSUE TITLE
Astronaut on the bike should come back | ipdb.io

### ISSUE THREAD

**Issue by muawiakh** [ipdb/site#21]
<img width="153" alt="screen shot 2017-09-26 at 1 56 33 pm" src="https://user-images.githubusercontent.com/8788382/30859140-b8103cca-a2c2-11e7-8eaf-9e5b376aa6bc.png">

We really like the website but: 

**Feature Request**
The astronaut on the bike just leaves the website and never comes back until we refresh page. I think we should use some key `space` to bring him back or start a `endless runner astronaut on a bike game` when user presses a certain combination.

Using the latest version of `ipdb.io`. 
**Steps to reproduce**: Visit `ipdb.io`.

**Comment by sbellem** [comment]
Also, change color each time it comes back. It could loop through a set of colors for instance.

**Comment by gmcmullen** [comment]
Strongly disagree. The astronaut has things to do. He would not be in such a hurry if he was not very busy. The astronaut does not want to be stuck in some vicious color-changing time loop for your amusement.

**Comment by muawiakh** [comment]
Closing this. Non issue. Should be tracked as part of `cool-unstable` release.
