### ISSUE TITLE
Add Links to IPDB Explorers

### ISSUE THREAD

**Issue by ttmc** [ipdb/site#31]
The idea is to add links to some IPDB Explorers.

There's this one by @nileshtrivedi

* GitHub: https://github.com/nileshtrivedi/bigchaindb-explorer
* Website: http://www.nileshtrivedi.com/bigchaindb-explorer/

and this one by the License.rocks team:

* GitHub: https://github.com/LicenseRocks/ipdb-explorer
* Website: https://ipdb-explorer.license.rocks/

**Comment by kremalicious** [comment]
Excellent idea. Also makes sense adding them to BDB Get Started page but as a first quick step I added them to get started section of IPDB front page in #32
