### ISSUE TITLE
add remaining content

### ISSUE THREAD

**Issue by kremalicious** [ipdb/site#5]
Just add in Markdown after the last `---` here:

- [ ] https://github.com/ipdb/site/edit/master/_src/foundation/articles.md
- [ ] https://github.com/ipdb/site/blob/master/_src/foundation/satzung.md
- [ ] https://github.com/ipdb/site/edit/master/_src/terms.md
- [x] https://github.com/ipdb/site/edit/master/_src/privacy.md
- [x] https://github.com/ipdb/site/edit/master/_src/imprint.md
- [x] https://github.com/ipdb/site/edit/master/_src/jobs.md

FAQ: https://beta.ipdb.io/faq/
That's coming from a data file, where you can use markdown in the answers too. Just delete question/answer blocks which don't make sense anymore:
- [ ] https://github.com/ipdb/site/edit/master/_src/_data/faq.yml

Also check the contact data and exact company name: https://beta.ipdb.io/contact/
- [x] https://github.com/ipdb/site/blob/master/_src/_data/contact.yml

**Comment by gmcmullen** [comment]
How do we want to handle the articles? The text is in a Word doc, and we need easy access to the English/German.

**Comment by gmcmullen** [comment]
Privacy and Terms - We are still working with the lawyers on this. Should have the final versions soon.

**Comment by kremalicious** [comment]
Pandoc should be able to quickly convert that docx:

```bash
brew install pandoc
pandoc -f docx -t markdown -o articles.md articles.docx
```

Otherwise just drop file on here and I try that. 

I'm tending towards keeping language versions on separate pages, and adding a note on top of default english version that the german version is the legally binding one. I know we loose this comparison feature with that but the majority of our users may not fit into the subset of people who understand both languages, and english is the default language of the site. Also didn't work on mobile and in future we might want to translate articles into another language too. 

Finally, it's much better for the machines to understand (don't wanna anger them), the web is a document & link-based medium and one document can only have one language assigned. But HTML provides mechanisms to link to alternative, language-versions of the same document, requiring them to be separate documents: https://support.google.com/webmasters/answer/189077?hl=en

**Comment by kremalicious** [comment]
prepared the Articles documents with proper interlinking between them, in `head` too. This is how it looks like:
- https://beta.ipdb.io/foundation/articles/
- https://beta.ipdb.io/foundation/satzung/

Foundation section could really use a proper submenu on the left side but current menu kinda works for now.
