### ISSUE TITLE
collect vector logos

### ISSUE THREAD

**Issue by kremalicious** [ipdb/site#7]
I need vector files for the following logos, ideally their horizontal versions. None of them make this available on their sites as far as I could see:

- [x] COALA
- [x] Human Data Commons Foundation
- [x] Dyne.org
- [x] unMonastery
- [ ] SmartContract
- [x] Tendermint
- [x] CREATE-NET

@gmcmullen do you have a contact for all of them? If so, could you reach out to them please?

Either drop logos onto this issue as a comment or drop on the Trello card: https://trello.com/c/q0HGMPx0/54-build-ipdbio-website-for-developers-reconcile-developersipdbio

**Comment by gmcmullen** [comment]
Sent request to all.

**Comment by gmcmullen** [comment]
[dyne.svg.zip](https://github.com/ipdb/site/files/1274649/dyne.svg.zip)

**Comment by gmcmullen** [comment]
[tendermint-logo.svg.zip](https://github.com/ipdb/site/files/1280214/tendermint-logo.svg.zip)

**Comment by gmcmullen** [comment]
[unmonastery-logo-ai.zip](https://github.com/ipdb/site/files/1280233/unmonastery-logo-ai.zip)

**Comment by gmcmullen** [comment]
[FBK-Create-net_vet.eps.zip](https://github.com/ipdb/site/files/1292289/FBK-Create-net_vet.eps.zip)

**Comment by gmcmullen** [comment]
Sent reminders to the outstanding groups.

**Comment by gmcmullen** [comment]
[HDC-svg.zip](https://github.com/ipdb/site/files/1320526/HDC-svg.zip)

**Comment by gmcmullen** [comment]
[Coala_Logo.pdf](https://github.com/ipdb/website/files/1355168/Coala_Logo.pdf)

**Comment by gmcmullen** [comment]
Also need: 

- [ ] Global Consent
- [x] KICTANet

**Comment by gmcmullen** [comment]
[LOGO KICTANET.pdf](https://github.com/ipdb/website/files/1355632/LOGO.KICTANET.pdf)
